# Python logging configuration - see https://docs.python.org/3/library/logging.config.html#configuration-dictionary-schema
version: 1
disable_existing_loggers: false
formatters:
  console:
    (): uvicorn.logging.ColourizedFormatter
    format: '%(levelprefix)s %(message)s'
  file:
    (): uvicorn.logging.DefaultFormatter
    format: '%(asctime)s %(levelname)s %(name)s %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
    use_colors: false
  access:
    (): uvicorn.logging.AccessFormatter
    format: '%(asctime)s %(levelname)s %(client_addr)s - "%(request_line)s" %(status_code)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
    use_colors: false
handlers:
  console:
    formatter: console
    class: logging.StreamHandler
    stream: ext://sys.stdout
  file:
    formatter: file
    class: logging.handlers.RotatingFileHandler
    filename: biograph.log
    maxBytes: 1024
    backupCount: 3
  access:
    formatter: access
    class: logging.handlers.RotatingFileHandler
    filename: access.log
    maxBytes: 1024
    backupCount: 3
root:
  handlers:
    - console
    - file
  level: INFO
loggers:
  uvicorn.access:
    handlers:
     - access
    level: INFO
    propagate: false
