# Python logging configuration - see https://docs.python.org/3/library/logging.config.html#configuration-dictionary-schema
version: 1
disable_existing_loggers: false
formatters:
  console:
    (): uvicorn.logging.ColourizedFormatter
    format: '%(levelprefix)s %(message)s'
  access:
    (): uvicorn.logging.AccessFormatter
    format: '%(levelprefix)s %(client_addr)s - "%(request_line)s" %(status_code)s'
handlers:
  console:
    formatter: console
    class: logging.StreamHandler
    stream: ext://sys.stdout
  access:
    formatter: access
    class: logging.StreamHandler
    stream: ext://sys.stdout
root:
  handlers:
    - console
  level: INFO
loggers:
  biograph:
    level: DEBUG
  uvicorn.access:
    handlers:
     - access
    level: INFO
    propagate: false
